"use client"
import { useEffect, useRef, useState } from "react"
const work=[['01','ALLBEE','OPERATING SYSTEM','Business infrastructure, finance, CRM, networks and AI.'],['02','SUPLAYKART','COMMERCE ENGINE','Quick commerce, inventory, logistics and the last mile.'],['03','HAJIZHAZ NETWORK','PROTOCOL','Proof-of-work infrastructure. HJZ. Built from first principles.'],['04','RKN ASSOCIATES','LEGAL DIGITAL','A legal practice translated into a precise digital product.'],['05','NAMMA ROAD','CIVIC TECHNOLOGY','Street-level reporting turned into actionable systems.']]
const disciplines=['LAW','CAPITAL','PRODUCT','ENGINEERING','AI','PROTOCOLS']
const stack=['NEXT.JS','REACT','TYPESCRIPT','POSTGRES','SUPABASE','VERCEL','GITHUB','RANDOMX','AI','SYSTEM DESIGN']
export default function Home(){const [menu,setMenu]=useState(false);const [active,setActive]=useState('HOME');const [time,setTime]=useState('');const hero=useRef<HTMLDivElement>(null)
useEffect(()=>{const move=(e:MouseEvent)=>{if(!hero.current)return;hero.current.style.setProperty('--mx',`${(e.clientX/innerWidth-.5)*2}`);hero.current.style.setProperty('--my',`${(e.clientY/innerHeight-.5)*2}`)};addEventListener('mousemove',move);const t=setInterval(()=>setTime(new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})),1000);return()=>{removeEventListener('mousemove',move);clearInterval(t)}},[])
useEffect(()=>{const els=[...document.querySelectorAll('[data-section]')];const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.getAttribute('data-section')||'HOME')),{rootMargin:'-40% 0px -45% 0px'});els.forEach(e=>o.observe(e));return()=>o.disconnect()},[])
const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)}
return <div className="world"><div className="noise"/><div className="progress"/><header className="top"><button className="logo" onClick={()=>go('home')}>H<span>/</span>H</button><nav className={menu?'show':''}>{['work','universe','thinking','now'].map(x=><button key={x} className={active===x.toUpperCase()?'sel':''} onClick={()=>go(x)}>{x}</button>)}</nav><div className="top-right"><span>CHENNAI / IN</span><span>{time||'00:00:00'}</span><button onClick={()=>go('contact')}>START A PROJECT ↗</button></div><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?'CLOSE':'MENU'}</button></header>
<main>
<section id="home" data-section="HOME" ref={hero} className="hero"><div className="hero-sky"/><div className="hero-object"><div className="halo h1"/><div className="halo h2"/><div className="core-glass"><i/><b>H</b></div><div className="axis x"/><div className="axis y"/></div><div className="hero-copy"><p className="micro"><i/> INDEPENDENT BUILDER / 2026</p><h1>BUILDING<br/><em>THE UNBUILT.</em></h1><p className="lede">I build companies, software and systems across technology, law and capital.<br/>Different worlds. One operating philosophy.</p><button className="enter" onClick={()=>go('intro')}><span>ENTER THE UNIVERSE</span><b>↓</b></button></div><div className="hero-meta"><span>SCROLL / EXPLORE</span><span>001 — 010</span></div><div className="hero-corner">HAJIHAZ<br/><small>BUILDING THE UNBUILT</small></div></section>
<section id="intro" data-section="INTRO" className="statement"><div className="label">01 / IDENTITY</div><div className="statement-grid"><h2>ONE PERSON.<br/><span>MULTIPLE WORLDS.</span></h2><div><p className="bigcopy">I build companies.<br/>I build software.<br/>I study law.<br/>I read markets.<br/>I test ideas.</p><p className="bodycopy">The thread connecting all of it is <strong>systems thinking.</strong> Understand the machine. Find the leverage. Build the thing that should exist.</p></div></div></section>
<section id="universe" data-section="UNIVERSE" className="universe"><div className="label">02 / THE UNIVERSE</div><div className="universe-head"><h2>EVERYTHING<br/><span>CONNECTS.</span></h2><p>Not a portfolio of unrelated projects.<br/>A network of systems, experiments and ideas.</p></div><div className="map"><div className="map-grid"/><div className="map-r r1"/><div className="map-r r2"/><div className="map-r r3"/><div className="map-core"><strong>HH</strong><span>HAJIHAZ</span></div>{disciplines.map((d,i)=><button key={d} className={`orbit-node n${i}`} onClick={()=>go('work')}><i/>{d}<small>0{i+1}</small></button>)}</div></section>
<section id="work" data-section="WORK" className="work"><div className="label">03 / SELECTED SYSTEMS</div><div className="work-head"><h2>BUILT<br/><span>FOR REAL.</span></h2><p>Products and infrastructure already in motion.<br/>Each project is an exercise in making complexity feel inevitable.</p></div><div className="works">{work.map(([num,name,type,desc],i)=><article key={name} className={`work-row r${i}`}><span className="num">{num}</span><div className="work-art"><div className="art-grid"/><div className="art-orb"/><div className="art-line"/></div><div className="work-info"><small>{type}</small><h3>{name}</h3><p>{desc}</p><button>VIEW SYSTEM ↗</button></div><span className="row-arrow">↗</span></article>)}</div></section>
<section className="architecture"><div className="label">04 / BUILDER MODE</div><div className="arch-grid"><div><h2>FROM IDEA<br/><span>TO SYSTEM.</span></h2><p>Interfaces are the visible layer. The real work is underneath: architecture, data, permissions, automation, failure states, economics and the details nobody sees.</p></div><div className="stack">{stack.map((s,i)=><span key={s}><b>0{i+1}</b>{s}</span>)}</div></div></section>
<section id="thinking" data-section="THINKING" className="thinking"><div className="label">05 / TECHNOLOGY × LAW × BUSINESS</div><div className="think-stage"><div className="giant">THINK<br/><i>IN</i><br/>SYSTEMS.</div><div className="think-side"><p>Understanding systems means understanding both <strong>how they are built</strong> and <strong>how they are governed.</strong></p>{['CONSTITUTIONAL LAW','CORPORATE SYSTEMS','TECHNOLOGY','GOVERNANCE','ENTREPRENEURSHIP'].map((x,i)=><div key={x}><small>0{i+1}</small>{x}<b>↗</b></div>)}</div></div></section>
<section className="markets"><div className="label">06 / CAPITAL & MARKETS</div><div className="terminal"><div className="term-head"><span>HH / MARKET DESK</span><span>DECISION &gt; NOISE</span></div><div className="term-title">CAPITAL IS<br/><i>A SYSTEM TOO.</i></div><div className="term-bottom"><p>Equities. Commodities. Macro. Risk.<br/><strong>Process over prediction.</strong></p><div className="signals">{['SIGNAL','RISK','CONTEXT','TIMING'].map((x,i)=><div key={x}><small>0{i+1}</small><b>{x}</b><span>{['Separate signal from noise.','Know what can break.','Zoom out before acting.','Patience is a position.'][i]}</span></div>)}</div></div></div></section>
<section className="lab"><div className="label">07 / HAJI LAB</div><div className="lab-title">EXPERIMENTS<br/><span>IN PUBLIC.</span></div><div className="ticker"><div>AI / BLOCKCHAIN / AUTOMATION / CIVIC TECH / FUTURE SYSTEMS / AI / BLOCKCHAIN / AUTOMATION / CIVIC TECH / FUTURE SYSTEMS /</div></div></section>
<section id="now" data-section="NOW" className="now"><div className="label">08 / RIGHT NOW</div><div className="now-grid"><h2>WHAT I'M<br/><span>BUILDING NOW.</span></h2><div>{[['HAJIZHAZ NETWORK','Protocol / PoW / HJZ'],['ALLBEE','Business OS / AI / Finance'],['SUPLAYKART','Commerce / Logistics'],['THIS PORTFOLIO','Identity / Interface / Experiment'],['LAW','LLB / Systems / Governance']].map(([a,b],i)=><article key={a}><small>0{i+1}</small><b>{a}</b><span>{b}</span><em>↗</em></article>)}</div></div></section>
<section className="future"><div className="label">09 / THE JOURNEY</div><div className="future-title">THE INTERESTING<br/><span>PART IS NEXT.</span></div><div className="journey"><div><b>01</b><strong>BUILD</strong><span>Ideas become systems.</span></div><div><b>02</b><strong>LEARN</strong><span>Engineering × law × markets.</span></div><div><b>03</b><strong>SCALE</strong><span>Products become ecosystems.</span></div><div><b>04</b><strong>NEXT</strong><span>Keep going.</span></div></div></section>
<section id="contact" data-section="CONTACT" className="contact"><div className="contact-red"/><div className="label">10 / CONTACT</div><div className="contact-main"><p>HAVE A<br/><i>BIG IDEA?</i></p><a href="mailto:hello@hajihaz.com">hello@hajihaz.com ↗</a></div><footer><span>HAJIHAZ © 2026</span><span>BUILDING THE UNBUILT.</span><div><a href="https://github.com/hajihaz/Hajihaz" target="_blank">GITHUB</a><a href="#">LINKEDIN</a><a href="#">X</a></div></footer></section>
</main></div>}
